dist: trusty
sudo: required

language: generic

addons:
  sonarcloud:
    organization: "nicolaspernoud-github"
    token:
      secure: "043UgXgLPkMJgjYuup1x8+IBF9ryDKVLL22aOD2I4/J410tCR4u5k6g9cPeV7rdZxRcZyeC1Y7xRkU2qxKjDutBNA09uRtGjAx32tcltu4DlMsErQhDxyvhP7IFUUr7vDQoD3WqWkPPT2LNs2Q1S4mKjdE4t58Pah3duTotsv5NtsAMEWtTTSpra0s0dZ9cRh6E8IfVA46+nMZIJYAXfUibkJehoWVWEiH1VJFZUIZaM/FYgHulzC0aaCdJ9ZbxFx6/xvbN5usqkMRg5R5QLz6i5JO3PUatE0dHOq4xiRDyXuX7i0uIuG7QyhM+FvqejCBzM4GGKgQ1s5MC3EaCLeIiggtWt4RgrACx09Blrwrp3llzK6pTc0xxNzVXSegOVksGit5ECgZ5hL52Hd/9P57Y8oFZyvs85Ka2fN0ZOgv4XwZBzvnlUsbWkeXsBanRGKzn1DCqK2XDX/y3glsdNI+9WSda71PvHWFvHgp+na1B/J16ZIEiXTdsnex3OiI3Djp4cVfeoI4TN6eLa55rcz+su5qHzRP/KHVzxoB+CBIHej6tTbZtnBDSjxud5oaQ9GuaUwV+JABjvx2r8QEuwxXO+S17SuH14ZWtkZQ9ZZrJpNlgdtMzZ8OmeufGP07H55BaYyqH6b6uJPB5pGdSQmGdzQe3KjO3tuTEC6fUOayg="
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.sonar/cache'

env:
  global:
    - secure: I6ATs+ZOJbXhtaBh8ga5ojmtQEo2IVQiMwN0+RoLRxOEh8sd7K60x+ooajHFfU4h8TgRBEmejT+MmmUrEU3Vllc53SD+Xc6ZOoeUL3mGbpOEcwcTEMMDOotdXo+NiDQRSZbcCyxS120nI2ZOUqCMcb5tb62q9rWCFcqO93JnXtL58rdZlqRlcMUlXpux5JUCx0q4ZxEPmcm4HzCkfQCk8+bAV0wItqsOvYdLNNHW/zLfibed5FcXGsiaByikjTuWtFgakj3UhglfgipEEJ97gwhd8lOIpij7lQWuaiC984FFYijLb6bpHMcOkGbJyTNt6Wv2DmcCm+KOpgjADvTpL0IwqJIE2ZSem1z+QZc1F09YQVH220ojOovD4/QRvieIupJwPbBeDIb6rcdpLcco1qbXpsXP+rjSSEh826fhRSsGBUrY0WhfygRZIoI0kUGNsZkkI9ofBZlEZQlQBB6gOI8WBCKpU0x6ky42Q4887FneYSSKOGVVXGEZOc8CdXLn+WbS1vd5EnOscMEg4aB36qtRkW2V6OK7vlCOOgMPVtNUDx/U8RqV/J8YxtJX9v7k6j4I/PyzNpzGYLrBHNCCfKxsfd7yMDmbvrRWE1l6IxnWRQOcyEDFERIU9Qf21/FDPdkwKO0JFXquL3ZZKd6fBabycnpxy8Mup6TZCrS3OZU=

services:
  - docker

script:
  # nsp scan
  - npm install nsp --global
  - nsp check server | true
  - nsp check client
  # sonarcloud scan
  - npm install typescript
  - sonar-scanner
  # prepare qemu
  - sudo apt install -y qemu qemu-user-static qemu-user binfmt-support
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # create container and push it to docker hub
  - set -e
  - export REPO=nicolaspernoud/ninicobox
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - echo $REPO:$TAG:$TRAVIS_BUILD_NUMBER
  - cp /usr/bin/qemu-arm-static ./
  - docker build -t $REPO:$TRAVIS_BUILD_NUMBER .
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $REPO:$TAG
  - docker push $REPO