sudo: required

language: generic

env:
  global:
    - secure: I6ATs+ZOJbXhtaBh8ga5ojmtQEo2IVQiMwN0+RoLRxOEh8sd7K60x+ooajHFfU4h8TgRBEmejT+MmmUrEU3Vllc53SD+Xc6ZOoeUL3mGbpOEcwcTEMMDOotdXo+NiDQRSZbcCyxS120nI2ZOUqCMcb5tb62q9rWCFcqO93JnXtL58rdZlqRlcMUlXpux5JUCx0q4ZxEPmcm4HzCkfQCk8+bAV0wItqsOvYdLNNHW/zLfibed5FcXGsiaByikjTuWtFgakj3UhglfgipEEJ97gwhd8lOIpij7lQWuaiC984FFYijLb6bpHMcOkGbJyTNt6Wv2DmcCm+KOpgjADvTpL0IwqJIE2ZSem1z+QZc1F09YQVH220ojOovD4/QRvieIupJwPbBeDIb6rcdpLcco1qbXpsXP+rjSSEh826fhRSsGBUrY0WhfygRZIoI0kUGNsZkkI9ofBZlEZQlQBB6gOI8WBCKpU0x6ky42Q4887FneYSSKOGVVXGEZOc8CdXLn+WbS1vd5EnOscMEg4aB36qtRkW2V6OK7vlCOOgMPVtNUDx/U8RqV/J8YxtJX9v7k6j4I/PyzNpzGYLrBHNCCfKxsfd7yMDmbvrRWE1l6IxnWRQOcyEDFERIU9Qf21/FDPdkwKO0JFXquL3ZZKd6fBabycnpxy8Mup6TZCrS3OZU=

services:
  - docker

script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - set -e
  - export REPO=nicolaspernoud/ninicobox
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - echo $REPO:$TAG:$TRAVIS_BUILD_NUMBER
  - docker build -t $REPO:$TRAVIS_BUILD_NUMBER .
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $REPO:$TAG
  - docker push $REPO